#pragma once
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using namespace winrt;
using namespace Windows::UI::Composition;
using namespace Windows::Foundation::Numerics;

namespace AnimatedVisuals
{
	class SquareCircleMorph //sealed //: public ICompositionSource
	{
	public:
		/* virtual Microsoft::UI::Xaml::Controls::IAnimatedVisual TryCreateAnimatedVisual(
			 Windows::UI::Composition::Compositor compositor,
			 Platform::Object^* diagnostics);*/

			 /*int32_t TryCreateInstance(Windows::UI::Composition::Compositor,
				 Windows::UI::Composition::Visual&,
				 Windows::Foundation::Numerics::float2&,
				 Windows::UI::Composition::CompositionPropertySet&,
				 Windows::Foundation::TimeSpan&);*/


		/*com_ptr<AnimatedVisual> TryCreateAnimatedVisual(
			Windows::UI::Composition::Compositor compositor,
			Platform::Object^* diagnostics);*/

			/*int32_t TryCreateInstance(Windows::UI::Composition::Compositor,
				Windows::UI::Composition::Visual&,
				Windows::Foundation::Numerics::float2&,
				Windows::UI::Composition::CompositionPropertySet&,
				Windows::Foundation::TimeSpan&);*/
		void TryCreateAnimatedVisual(
			Compositor const& compositor, VisualCollection const& visuals);
		void Play();

	private:
		ScalarKeyFrameAnimation progressAnimation{ nullptr };
		Compositor mCompositor{nullptr};
		void* thing; //temp hack
	};
}